CREATE TABLE FavoriteMovie (
FavoriteMovieId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
MoviePostId UNIQUEIDENTIFIER NOT NULL,
IdentityUserId NVARCHAR(450) NOT NULL,
CreatedAt DATETIME NOT NULL,
UpdatedAt DATETIME DEFAULT GETDATE() NOT NULL
CONSTRAINT FK_FavoriteMovie_UserIdentity FOREIGN KEY (IdentityUserId) REFERENCES dbo.AspNetUsers(Id),
CONSTRAINT FK_FavoriteMovie_MoviePost FOREIGN KEY (MoviePostId) REFERENCES dbo.MoviePost(MoviePostId)
)