CREATE TABLE Comment (
 CommentId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
 RatingId UNIQUEIDENTIFIER NOT NULL,
 IdentityUserId NVARCHAR(450) NOT NULL,
 Content NVARCHAR(MAX) NOT NULL,
 CreatedAt DATETIME DEFAULT GETDATE() NOT NULL,
 UpdatedAt DATETIME DEFAULT GETDATE() NOT NULL
 CONSTRAINT FK_Comment_UserIdentity FOREIGN KEY (IdentityUserId) REFERENCES dbo.AspNetUsers(Id),
 CONSTRAINT FK_Comment_PostComment FOREIGN KEY (RatingId) REFERENCES dbo.MovieRating(RatingId)
)