CREATE TABLE Wishlist (
WishlistId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
MoviePostId UNIQUEIDENTIFIER NOT NULL,
IdentityUserId NVARCHAR(450) NOT NULL,
WishlistName NVARCHAR(150) NOT NULL,
AddedAt DATETIME NOT NULL,
UpdatedAt DATETIME DEFAULT GETDATE() NOT NULL
CONSTRAINT FK_Wishlist_UserIdentity FOREIGN KEY (IdentityUserId) REFERENCES dbo.AspNetUsers(Id),
)